services:
  postgres-admin:
    image: postgres:18beta3
    container_name: ygg-postgres-admin
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd123
    ports:
      - "5432:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: ygg-redis
    command: redis-server --requirepass P@ssw0rd123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "P@ssw0rd123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_admin_data:
  redis_data: